name: Release
on:
  create:
    tags:
    - 'v*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn publish
      env:
        GITHUB_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}